version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/tokinoidb
      - DATABASE_USERNAME=tokinoi
      - DATABASE_PASSWORD=123456
    depends_on:
      - db
  db:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_DB=tokinoidb
      - POSTGRES_USER=tokinoi
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_api:/var/lib/postgresql/data

volumes:
  postgres_api:
