spring:
  application:
    name: tokinoi-gallery-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  jwt:
    secret: HfTKhE+O5VPLbbQX/sTH1r/ZIC/duRxXk3hiCmrfdqOzXB5L+FLluZOKzAT5LPS9ku8naeiA3Xze+BuTphJFfg==
    expiration-time: 86400000
file:
  upload-path: uploads