spring:
  application:
    name: tokinoi-gallery-app
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5433/tokinoidb
    password: 123456db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
